---
permalink: install/concept_dependency_between_zone_and_host_group_definitions.html 
sidebar: sidebar 
keywords: dependency, between, zone, host, group, definitions, common, errors, cascading, effect 
summary: 如果在分区定义中发生错误、则可能需要重新配置主机组定义、反之亦然。 
---
= 区域和主机组定义之间的依赖关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在分区定义中发生错误、则可能需要重新配置主机组定义、反之亦然。

构建分区定义时、会指定两个端口：ONTAP系统上FC启动程序端口的WWPN以及该分区的存储阵列端口WWPN或WWNN。同样、在存储阵列上配置ONTAP系统的主机组时、系统会指定要成为主机组成员的FC启动程序端口的WWPN。

典型的配置顺序如下：

. 构建分区定义。
. 在存储阵列上构建主机组(从选择列表中选取ONTAP系统上FC启动程序端口的WWPN)。
. 向端口提供阵列LUN。


但是、有时、主机组会在分区定义之前进行配置、这需要在存储阵列的主机组配置中手动输入WWPN。



== 常见错误

在ONTAP输出中，ONTAP系统上的FC启动程序端口通过适配器编号来标识，例如0a、0b、0c、0d、 等适用于具有板载端口的型号。WWPN显示在交换机GUI和存储阵列GUI中。由于WWPN较长、采用十六进制格式、因此经常出现以下错误：

[cols="2*"]
|===
| 如何指定WWPN | 常见错误 


 a| 
管理员以WWPN形式键入
 a| 
出现键入错误。



 a| 
交换机会自动发现WWPN
 a| 
从选择列表中选择的FC启动程序端口WWPN不正确。

|===
[NOTE]
====
将ONTAP系统、交换机和存储阵列连接在一起后、交换机会自动发现ONTAP系统的WWPN和存储阵列端口。然后、WWPN将显示在交换机图形用户界面的选择列表中、从而可以选择每个区域成员的WWPN、而无需键入WWPN。为了消除键入错误的可能性、建议交换机发现WWPN。

====


== 错误的级联影响

在排除光纤连接配置问题时、显而易见的第一步是检查分区配置是否正确。考虑主机组与区域定义之间的关系也很重要。修复问题可能需要重新配置分区定义和主机组定义、具体取决于配置过程中出错的位置。

如果交换机自动发现WWPN、并且首先配置了分区定义、则用于访问存储阵列上LUN的FC启动程序端口的WWPN会自动传播到存储阵列图形用户界面中的主机组配置选择列表。因此、任何分区错误也会传播到存储阵列主机组选择列表。选择列表显示的是长的十六进制WWPN、而不是ONTAP系统上可见的短FC启动程序端口标签(例如0a、0b等)。因此、您预计要列出的WWPN不存在并不容易。

下表显示了某些错误的影响：

[cols="3*"]
|===
| 交换机上的分区定义 | 存储阵列上的主机组配置 | ONTAP输出中的症状 


 a| 
分区定义中的FC启动程序端口不正确。这会导致将不正确的FC启动程序端口WWPN传播到主机组配置。
 a| 
选择了选择列表中显示的FC启动程序端口的WWPN、而不是所需的WWPN。
 a| 
在可以看到预期LUN的FC启动程序端口上、无法看到阵列LUN。



 a| 
分区定义包括正确的FC启动程序端口。
 a| 
由于以下任一原因、主机组定义中的WWPN不正确：

* 选择的WWPN不正确。
* 主机组是在配置分区定义之前手动配置的、并且在键入FC启动程序端口的WWPN时出现键入错误。

 a| 

|===