---
permalink: install/reference_the_storage_errors_show_messages_and_their_resolution.html 
sidebar: sidebar 
keywords: storage, errors, show, messages, resolution 
summary: 当storage error show标记错误情况时、您需要确定发生错误的原因以及如何修复错误。 
---
= 存储错误会显示相关消息及其解决方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在标记错误条件时 `storage errors show` 、您需要确定发生错误的原因以及如何修复错误。

下表列出了检测到的后端配置错误 `storage errors show` 、并提供了有关每个错误的原因及其解决方法的详细信息。

|===
| `storage errors show` 消息 | 有关此消息的详细信息、请参见... 


 a| 
`NAME (Serial #): All paths to this array LUN are connected to the same fault domain. This is a single point of failure``(英文)
 a| 
xref:reference_all_paths_to_an_array_lun_are_on_the_same_storage_array_controller.adoc[一个阵列LUN的所有路径都位于同一个存储阵列控制器上]



 a| 
`NAME (Serial #), port WWPN1: LUN 1 occurs more than once. LUNs cannot be reused on the same array target port`(英文)
 a| 
xref:reference_duplicate_lun_ids_on_a_target_port.adoc[目标端口上的LUN ID重复]



 a| 
`NAME (Serial #): This array LUN is an access control LUN. It is not supported and should be masked off or disabled``(英文)
 a| 
xref:reference_an_access_control_lun_is_presented_to_ontap.adoc[已提供访问控制LUN]



 a| 
`NAME (Serial #) This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode`(英文)
 a| 
xref:reference_array_luns_are_configured_with_conflicting_failover_modes_clustered_data_ontap_8_2_and_later.adoc[阵列LUN配置有冲突的故障转移模式]



 a| 
`NAME (Serial #): This Array LUN is only available on one path. Proper configuration requires two paths`(英文)
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[一个阵列LUN的路径少于两个]



 a| 
`NAME (Serial #): This array LUN is too large and is not usable. The maximum array LUN size supported is xTB`(英文)
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[阵列LUN太小或太大]



 a| 
`NAME (Serial #): This array LUN is too small and is not usable. The minimum array LUN size supported is 1GB`(英文)
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[阵列LUN太小或太大]



 a| 
`NAME (Serial #): This Array LUN is using multiple LUN IDs. Only one LUN ID per serial number is supported`(英文)
 a| 
xref:reference_lun_ids_for_the_same_ldev_do_not_match.adoc[同一LEV的LUN ID不匹配]

卷集寻址不一致



 a| 
`NAME (Serial #): This array LUN is marked foreign and has a reservation`(英文)
 a| 
xref:reference_array_lun_is_marked_foreign_and_has_a_reservation_data_ontap_8_3_and_later.adoc[阵列LUN标记为外部并具有预留]

|===