---
permalink: implement-third-party/reference_workaround_for_the_unknown_device_l254_ses_problem_with_3par_storage_arrays.html 
sidebar: sidebar 
keywords: 'Workaround, unknown device (l254/ses), problem, 3PAR, storage, arrays, aggregates, luns, created, ontap system, not' 
summary: '在对交换机进行分区以将ONTAP系统连接到3PAR存储阵列之前、应在3PAR存储阵列上创建主机定义、并在"使用ONTAP系统的3PAR阵列所需参数"部分中指定主机角色。如果在定义主机之前配置了分区、则ONTAP会发现3PAR阵列LUN为LUN 254和产品类型SES、而ONTAP无法使用这些LUN。' 
---
= 3CAR存储阵列的未知设备(L254/SES)问题的解决方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在对交换机进行分区以将ONTAP系统连接到3PAR存储阵列之前、应在3PAR存储阵列上创建主机定义、并在"使用ONTAP系统的3PAR阵列所需参数"部分中指定主机角色。如果在定义主机之前配置了分区、则ONTAP会发现3PAR阵列LUN为LUN 254和产品类型SES、而ONTAP无法使用这些LUN。

xref:reference_required_parameters_for_3par_arrays_with_data_ontap_systems.adoc[使用ONTAP系统的3PAR阵列所需的参数]

当ONTAP发现3PAR阵列LUN为LUN 254且产品类型为SES时、新映射的3PAR LUN无法分配给ONTAP系统、并且某些可能已添加到聚合的3PAR LUN无法使用、因为ONTAP会发现LUN 254。ONTAP会为其发现的LUN (LUN 254和产品类型SES)生成EMS消息、并将某些LUN报告为未知设备。

如果在定义主机之前配置了分区、则可以通过强制重新发现从3CAR存储阵列映射的阵列LUN来解决LUN 254/SES未知设备问题。您使用的过程取决于是否已在ONTAP系统上配置具有3PAR阵列LUN的聚合。(在以下过程中、假设节点1和节点2是ONTAP节点的名称。)



== 如果已在ONTAP系统上创建包含3PAR阵列LUN的聚合

. 运行以下命令、确保已在ONTAP系统上启用HA配置： *`cluster ha show`*
+
此时将显示以下输出：

+
[listing]
----

High Availability Configured: true
----
. 运行以下命令、确保已在ONTAP系统上配置存储故障转移： *`storage failover show`*
+
此时将显示以下输出：

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-1    Node-2    true     Connected to Node-2
Node-2    Node-1    true     Connected to Node-1
2 entries were displayed.
----
. 运行以下命令、对节点1执行接管操作： *`storage failover takeover -ofnode Node-1`*
. 再次运行以下命令、以验证节点2是否已准备好进行恢复操作： *`storage failover show`*
+
此时将显示以下输出：

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-2    Node-1    false    In takeover, Auto giveback will be
                                      initiated in 348 seconds
Node-1    Node-2    -        Waiting for giveback (HA mailboxes)
2 entries were displayed.
----
. 运行以下命令、在节点1上执行一个回给操作： *`storage failover giveback -ofnode Node-1 -require-partner-waiting true`*
. 在集群中的其他节点上、重复步骤3到步骤5。




== 如果尚未在ONTAP系统上创建包含3PAR阵列LUN的聚合

. 运行以下命令以列出连接到3PAR存储阵列的所有ONTAP FC启动程序端口： *`system node run -node <node name> -command "sysconfig -v"`*
+
以下示例显示了包含特定节点名称的命令： *`system node run -node Node-1 -command "sysconfig -v"`*

. 运行以下命令、使列出的所有端口脱机： *`system node run -node <node name> -command "priv set advanced;fcadmin offline <adapter>"`*
+
以下示例显示了包含特定节点名称和适配器的命令： *`system node run -node Node-1 -command "priv set advanced;fcadmin offline 0a"`*

. 运行以下命令、使列出的所有端口联机： *`system node run -node <node name> -command "priv set advanced;fcadmin online <adapter>"`*
+
以下示例显示了包含特定节点名称和适配器的命令： *`system node run -node Node-1 -command "priv set advanced;fcadmin online 0a"`*


