---
permalink: implement-third-party/reference_workaround_when_luns_are_not_visible_with_hitachi_storage_arrays.html 
sidebar: sidebar 
keywords: workaround, luns, not, visible, hitachi, storage, arrays, aggregates, created, ontap, system, 
summary: '在对交换机进行分区之前、应设置"Required parameters for Hitachi storage arra如 使用运行ONTAP的系统的Hitachi存储阵列"部分中指定的存储阵列参数、并将LUN映射到主机组、以便将使用阵列LUN的ONTAP系统连接到Hitachi存储阵列。' 
---
= 在Hitachi存储阵列中看不到LUN时的解决方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在对交换机进行分区之前、应设置"Required parameters for Hitachi storage arra如 使用运行ONTAP的系统的Hitachi存储阵列"部分中指定的存储阵列参数、并将LUN映射到主机组、以便将使用阵列LUN的ONTAP系统连接到Hitachi存储阵列。

xref:reference_required_parameters_for_hitachi_storage_arrays_with_ontap_systems.adoc[系统运行ONTAP时Hitachi存储阵列的必需参数]

如果在设置参数并将LUN映射到主机组之前配置了分区、则可以通过执行路径重新初始化来解决LUN不可见的问题。路径重新初始化会强制重新发现从Hitachi存储阵列映射的阵列LUN。

您使用的过程取决于是否已在ONTAP系统上配置使用Hitachi阵列LUN的聚合。(在以下过程中、假设节点1和节点2是ONTAP节点的名称。)



== 如果在使用阵列LUN的ONTAP系统上已创建包含Hitachi阵列LUN的聚合

. 运行以下命令、确保已在ONTAP系统上启用HA配置： *`cluster ha show`*
+
此时将显示以下输出：

+
[listing]
----

High Availability Configured: true
----
. 运行以下命令、确保已在ONTAP系统上配置存储故障转移： *`storage failover show`*
+
此时将显示以下输出：

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-1    Node-2    true     Connected to Node-2
Node-2    Node-1    true     Connected to Node-1
2 entries were displayed.
----
. 运行以下命令对节点1执行接管操作： *`storage failover takeover -ofnode Node-1`*
. 再次运行以下命令、以验证节点2是否已准备好进行恢复操作： *`storage failover show`*
+
此时将显示以下输出：

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-2    Node-1    false    In takeover, Auto giveback will be
                                      initiated in 348 seconds
Node-1    Node-2    -        Waiting for giveback (HA mailboxes)
2 entries were displayed.
----
. 运行以下命令、对节点1执行一次回给操作： *`storage failover giveback -ofnode Node-1 -require-partner-waiting true`*
. 在集群中的其他节点上、重复步骤3到步骤5。




== 如果尚未在使用阵列LUN的ONTAP系统上创建包含Hitachi阵列LUN的聚合

. 运行以下命令、列出连接到Hitachi存储阵列的所有ONTAP FC启动程序端口： *`system node run -node <node name> -command "sysconfig -v"`*
+
例如： *`system node run -node Node-1 -command "sysconfig -v"`*

. 运行以下命令、使列出的所有端口脱机： *`system node run -node <node name> -command "priv set advanced;fcadmin offline <adapter>"`*
+
例如： *`system node run -node Node-1 -command "priv set advanced;fcadmin offline 0a"`*

. 运行以下命令、使列出的所有端口联机： *`system node run -node <node name> -command "priv set advanced;fcadmin online <adapter>"`*
+
例如： *`system node run -node Node-1 -command "priv set advanced;fcadmin online 0a"`*


